version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: sudo apt-get update && sudo apt-get install -y unzip rsync bc
      - run:
          name: Tinkerboard-Build
          command: make PRODUCT=raspmatic_tinkerboard release
