blank_issues_enabled: false
contact_links:
  - name: RaspberryMatic Community Support
    url: https://homematic-forum.de/forum/viewforum.php?f=65
    about: Please ask and answer questions in the RaspberryMatic fora here.
