name: CI
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        platform: [rpi0, rpi3, rpi4, tinkerboard, intelnuc]
    
    steps:
    - uses: actions/checkout@v1

    - name: build raspmatic_${{ matrix.platform }}
      #run: make raspmatic_${{ matrix.platform }}-release
      run: |
        echo ::set-env name=VERSION::$(cat VERSION)
        ls -la .
        echo $VERSION
        echo "TEST" >release/RaspberryMatic-$VERSION-${{ matrix.platform }}.zip
        ls -la release/

    - name: upload snapshot
      uses: WebFreak001/deploy-nightly@master
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/jens-maus/RaspberryMatic/releases/22744592/assets{?name,label}
        release_id: 22744592
        asset_path: release/RaspberryMatic-${{ env.VERSION }}-${{ matrix.platform }}.zip
        asset_name: RaspberryMatic-$$-${{ matrix.platform }}.zip
        asset_content_type: application/zip
        max_releases: 5
