name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      GITHUB_SHA8: ${GITHUB_SHA::8}

    strategy:
      fail-fast: false
      matrix:
        platform: [rpi0, rpi3, rpi4, tinkerboard, intelnuc, ova]
    
    steps:
    - uses: actions/checkout@v2

    - name: rename worker directory
      working-directory: ../
      run: |
        mv RaspberryMatic b
        ln -s b RaspberryMatic

    - name: set env
      run: echo ::set-env name=VERSION::$(cat VERSION)

    #- name: remote debug tmate session
    #  uses: mxschmitt/action-tmate@v1
    #  if: matrix.platform == 'ova'

    - name: build raspmatic_${{ matrix.platform }}
      run: make raspmatic_${{ matrix.platform }}-release
      #run: |
      #  ls -la .
      #  echo ${{ env.VERSION }}
      #  echo "TEST" >release/RaspberryMatic-${{ env.VERSION }}-${{ matrix.platform }}.zip
      #  sha256sum release/RaspberryMatic-${{ env.VERSION }}-${{ matrix.platform }}.zip >release/RaspberryMatic-${{ env.VERSION }}-${{ matrix.platform }}.zip.sha256
      #  ls -la release/

    - name: upload build as artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ env.GITHUB_SHA8 }}-${{ matrix.platform }}
        path: release/RaspberryMatic-${{ env.VERSION }}-${{ matrix.platform }}.zip

    - name: upload nightly build archive
      if: github.event_name == 'schedule'
      uses: WebFreak001/deploy-nightly@master
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/jens-maus/RaspberryMatic/releases/22744592/assets{?name,label}
        release_id: 22744592
        asset_path: release/RaspberryMatic-${{ env.VERSION }}-${{ matrix.platform }}.zip
        asset_name: RaspberryMatic-$$-${{ matrix.platform }}.zip
        asset_content_type: application/zip
        max_releases: 5

    - name: upload nightly build checksum
      if: github.event_name == 'schedule'
      uses: WebFreak001/deploy-nightly@master
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/jens-maus/RaspberryMatic/releases/22744592/assets{?name,label}
        release_id: 22744592
        asset_path: release/RaspberryMatic-${{ env.VERSION }}-${{ matrix.platform }}.zip.sha256
        asset_name: RaspberryMatic-$$-${{ matrix.platform }}.zip.sha256
        asset_content_type: text/plain
        max_releases: 5
