name: CI
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        platform: [raspmatic_rpi0, raspmatic_rpi3, raspmatic_rpi4, raspmatic_tinkerboard, raspmatic_intelnuc]
    
    steps:
    - uses: actions/checkout@v1

    - name: build ${{ matrix.platform }}
      run: make ${{ matrix.platform }}-release

    - name: upload snapshot
      uses: WebFreak001/deploy-nightly@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/jens-maus/RaspberryMatic/releases/22744592/assets{?name,label}
        release_id: 22744592
        asset_path: ./release/RaspberryMatic-3.*.zip
        asset_name: RaspberryMatic-nightly-$$.zip
        asset_content_type: application/zip
        max_releases: 5
