name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [raspmatic_rpi0, raspmatic_rpi3, raspmatic_rpi4, raspmatic_tinkerboard, raspmatic_ova]
    
    steps:
    - uses: actions/checkout@v1
    - name: build ${{ matrix.platform }}
      run: make -j3 ${{ matrix.platform }} 2>&1 >/dev/null
